name: Build LaTeX document

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@master
      with:
        root_file: main.tex
        compiler: xelatex
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    - name: Check pdf files
      run: |
        file main.pdf | grep -q ' PDF '
    - name: Rename pdf file
      run: |
        DATE=$(date +%Y-%m-%d)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        mv main.pdf "main_${DATE}_${COMMIT_HASH}.pdf"
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: main.pdf
        path: "main_${DATE}_${COMMIT_HASH}.pdf"